// <auto-generated />
namespace TrashCollector2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactoredMonthlyPaymentfromcustomermodeltoPickupModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoredMonthlyPaymentfromcustomermodeltoPickupModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710311919557_refactored MonthlyPayment from customer model to Pickup Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
