// <auto-generated />
namespace TrashCollector2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcityandstatecolumnforpickupsandaddedattributetoaddressrelatedinformation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcityandstatecolumnforpickupsandaddedattributetoaddressrelatedinformation));
        
        string IMigrationMetadata.Id
        {
            get { return "201710301842124_added city and state column for pickups and added attribute to address related information"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
