// <auto-generated />
namespace TrashCollector2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedPaymentnametoWeeklyPayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedPaymentnametoWeeklyPayment));
        
        string IMigrationMetadata.Id
        {
            get { return "201711062020099_changed Payment name to WeeklyPayment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
