// <auto-generated />
namespace TrashCollector2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedapickupstatuscolumntopickupmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedapickupstatuscolumntopickupmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710271413084_added a pickup status column to pickup model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
