// <auto-generated />
namespace TrashCollector2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removingforeignkeysforcontrollercreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removingforeignkeysforcontrollercreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261406299_removing foreign keys for controller creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
