// <auto-generated />
namespace TrashCollector2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactoredcustomersmodelandaddedapickupmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoredcustomersmodelandaddedapickupmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261617306_refactored customers model and added a pickup model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
