// <auto-generated />
namespace TrashCollector2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdanumberofassignedandactivepickupsforcustomers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdanumberofassignedandactivepickupsforcustomers));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061751133_created a number of assigned and active pickups for customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
